enum PostsActionsTypes {
  FETCH_POSTS_START = "FETCH_POSTS_START",
  FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE",

  FETCH_POST_START = "FETCH_POST_START",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "FETCH_POST_FAILURE",

  CREATE_POST_START = "CREATE_POST_START",
  CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE = "CREATE_POST_FAILURE",

  SAVE_POST_START = "SAVE_POST_START",
  SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS",
  SAVE_POST_FAILURE = "SAVE_POST_FAILURE",

  DELETE_POST_START = "DELETE_POST_START",
  DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE = "DELETE_POST_FAILURE",
}

export default PostsActionsTypes
