enum PostEditActionsTypes {
  POST_EDIT_LOAD_POST = "POST_EDIT_LOAD_POST",

  POST_EDIT_EDIT_POST = "POST_EDIT_EDIT_POST",

  POST_EDIT_EDIT_POST_VALUES = "POST_EDIT_EDIT_POST_VALUES",
  POST_EDIT_EDIT_POST_CONTENT = "POST_EDIT_EDIT_POST_CONTENT",

  POST_EDIT_FETCH_POST_START = "POST_EDIT_FETCH_POST_START",
  POST_EDIT_FETCH_POST_SUCCESS = "POST_EDIT_FETCH_POST_SUCCESS",
  POST_EDIT_FETCH_POST_FAILURE = "POST_EDIT_FETCH_POST_FAILURE",

  POST_EDIT_UPDATE_POST_IS_SAVE = "POST_EDIT_UPDATE_POST_IS_SAVE",
}

export default PostEditActionsTypes
