enum LocalSettingsActionsTypes {
  LOCAL_SETTINGS_TOGGLE_NAVBAR_ACTIVE = "LOCAL_SETTINGS_TOGGLE_NAVBAR_ACTIVE",
  LOCAL_SETTINGS_SHOW_POP_UP_CARD = "LOCAL_SETTINGS_SHOW_POP_UP_CARD",
  LOCAL_SETTINGS_HIDE_POP_UP_CARD = "LOCAL_SETTINGS_HIDE_POP_UP_CARD",
}

export default LocalSettingsActionsTypes
