enum AuthActionsTypes {
  AUTH_INITIAL_PROCESS_COMPLETED = "AUTH_INITIAL_PROCESS_COMPLETED",
  AUTH_CHECK_USER_SESSION = "AUTH_CHECK_USER_SESSION",

  AUTH_SIGN_IN_START = "AUTH_SIGN_IN_START",
  AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS",
  AUTH_SIGN_IN_FAILURE = "AUTH_SIGN_IN_FAILURE",

  AUTH_SIGN_UP_START = "AUTH_SIGN_UP_START",
  AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS",
  AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE",

  AUTH_SIGN_OUT_START = "AUTH_SIGN_OUT_START",
  AUTH_SIGN_OUT_SUCCESS = "AUTH_SIGN_OUT_SUCCESS",
  AUTH_SIGN_OUT_FAILURE = "AUTH_SIGN_OUT_FAILURE",

  AUTH_TOGGLE_PUBLISHED_POSTS_START = "AUTH_TOGGLE_PUBLISHED_POSTS_START",
  AUTH_TOGGLE_PUBLISHED_POSTS_SUCCESS = "AUTH_TOGGLE_PUBLISHED_POSTS_SUCCESS",
  AUTH_TOGGLE_PUBLISHED_POSTS_FAILURE = "AUTH_TOGGLE_PUBLISHED_POSTS_FAILURE",

  AUTH_TOGGLE_PUBLISHED_POSTS_LIST_START = "AUTH_TOGGLE_PUBLISHED_POSTS_LIST_START",
  AUTH_TOGGLE_PUBLISHED_POSTS_LIST_SUCCESS = "AUTH_TOGGLE_PUBLISHED_POSTS_LIST_SUCCESS",
  AUTH_TOGGLE_PUBLISHED_POSTS_LIST_FAILURE = "AUTH_TOGGLE_PUBLISHED_POSTS_LIST_FAILURE",
}

export default AuthActionsTypes
